apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replicaset
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-pod
          image: nginx
          ports:
            - containerPort: 4000

